# Travis-CI Build for IcemanFork/Proxmark3
language: c

#default linux build env is: Ubuntu 14.04 trusty
dist: trusty
sudo: required

#install:
compiler: gcc

services:
  - docker

# multi platform build test
# build matrix,  
# LINUX : Using trusty beta build environment,  based on Ubuntu 14.04
# MAC OS: 
matrix:
  include:
    - os: osx
      osx_image: xcode7.3
  allow_failures:
    - os: osx

before_install:
  - docker build -t $DOCKER_USERNAME/proxmark3 .

## Install mainline ARM toolchain.  gcc-arm-none-eabi is available
## in Ubuntu >= 14.04, but this external PPA is needed for 12.04.
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty main universe multiverse restricted'; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y gcc-arm-none-eabi; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git fetch --all; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install perl; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap iceman1001/proxmark3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install proxmark3; fi

after_success:
  # source: https://docs.travis-ci.com/user/docker/#Pushing-a-Docker-Image-to-a-Registry
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push $DOCKER_USERNAME/proxmark3;
    fi

script: "make all"