#!/bin/bash



dev=$(ls -1 /dev/tty.usbmodem*)

client/flasher $dev armsrc/obj/fullimage.elf &

sleep 6 && pkill flasher

dev=$(ls -1 /dev/tty.usbmodem*)

client/flasher $dev  armsrc/obj/fullimage.elf

#sleep 5 

#dev=$(ls -1 /dev/tty.usbmodem*)

